/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AccountApplication = IDL.Record({
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'accountType' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ContactFormSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const LoanApplication = IDL.Record({
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'loanType' : IDL.Text,
  'amount' : IDL.Float64,
});
export const Transaction = IDL.Record({
  'date' : IDL.Text,
  'description' : IDL.Text,
  'isDeposit' : IDL.Bool,
  'amount' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'applyForAccount' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'applyForLoan' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deposit' : IDL.Func([IDL.Float64, IDL.Text, IDL.Text], [], []),
  'getAccountApplications' : IDL.Func(
      [],
      [IDL.Vec(AccountApplication)],
      ['query'],
    ),
  'getBalance' : IDL.Func([], [IDL.Float64], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactForms' : IDL.Func([], [IDL.Vec(ContactFormSubmission)], ['query']),
  'getLoanApplications' : IDL.Func([], [IDL.Vec(LoanApplication)], ['query']),
  'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'withdraw' : IDL.Func([IDL.Float64, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AccountApplication = IDL.Record({
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'accountType' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ContactFormSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const LoanApplication = IDL.Record({
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'loanType' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const Transaction = IDL.Record({
    'date' : IDL.Text,
    'description' : IDL.Text,
    'isDeposit' : IDL.Bool,
    'amount' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'applyForAccount' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'applyForLoan' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deposit' : IDL.Func([IDL.Float64, IDL.Text, IDL.Text], [], []),
    'getAccountApplications' : IDL.Func(
        [],
        [IDL.Vec(AccountApplication)],
        ['query'],
      ),
    'getBalance' : IDL.Func([], [IDL.Float64], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactForms' : IDL.Func(
        [],
        [IDL.Vec(ContactFormSubmission)],
        ['query'],
      ),
    'getLoanApplications' : IDL.Func([], [IDL.Vec(LoanApplication)], ['query']),
    'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'withdraw' : IDL.Func([IDL.Float64, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };