/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AccountApplication {
  'fullName' : string,
  'email' : string,
  'accountType' : string,
}
export interface ContactFormSubmission {
  'name' : string,
  'email' : string,
  'message' : string,
}
export interface LoanApplication {
  'fullName' : string,
  'email' : string,
  'loanType' : string,
  'amount' : number,
}
export interface Transaction {
  'date' : string,
  'description' : string,
  'isDeposit' : boolean,
  'amount' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'applyForAccount' : ActorMethod<[string, string, string], undefined>,
  'applyForLoan' : ActorMethod<[string, string, string, number], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deposit' : ActorMethod<[number, string, string], undefined>,
  'getAccountApplications' : ActorMethod<[], Array<AccountApplication>>,
  'getBalance' : ActorMethod<[], number>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactForms' : ActorMethod<[], Array<ContactFormSubmission>>,
  'getLoanApplications' : ActorMethod<[], Array<LoanApplication>>,
  'getTransactions' : ActorMethod<[], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitContactForm' : ActorMethod<[string, string, string], undefined>,
  'withdraw' : ActorMethod<[number, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];