/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AccountApplication {
  'fullName' : string,
  'email' : string,
  'accountType' : string,
}
export interface AdvisoryBooking {
  'consultationTopic' : string,
  'name' : string,
  'businessType' : string,
  'preferredDate' : string,
}
export interface BusinessAccount {
  'incomingPayments' : Array<BusinessPayment>,
  'outgoingPayments' : Array<BusinessPayment>,
  'businessBalance' : number,
}
export interface BusinessLoanApplication {
  'status' : LoanStatus,
  'businessName' : string,
  'businessType' : string,
  'submittedAt' : string,
  'loanAmountRequested' : number,
  'annualRevenue' : number,
  'loanPurpose' : string,
}
export interface BusinessPayment {
  'date' : string,
  'recipient' : string,
  'description' : string,
  'amount' : number,
}
export interface ContactFormSubmission {
  'name' : string,
  'email' : string,
  'message' : string,
}
export interface LoanApplication {
  'fullName' : string,
  'email' : string,
  'loanType' : string,
  'amount' : number,
}
export type LoanStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface PayrollRecord {
  'employeeName' : string,
  'salaryAmount' : number,
  'paymentDate' : string,
}
export interface SavingsAccountInfo {
  'lastInterestCredited' : string,
  'balance' : number,
  'accountId' : string,
  'totalInterestEarned' : number,
  'createdAt' : string,
  'updatedAt' : string,
  'interestRate' : number,
}
export interface Transaction {
  'date' : string,
  'description' : string,
  'isDeposit' : boolean,
  'amount' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminGetAdvisoryBookings' : ActorMethod<[], Array<AdvisoryBooking>>,
  'adminGetAllBusinessLoanApplications' : ActorMethod<
    [],
    Array<[Principal, Array<BusinessLoanApplication>]>
  >,
  'adminUpdateBusinessLoanStatus' : ActorMethod<
    [bigint, LoanStatus, Principal],
    undefined
  >,
  'applyForAccount' : ActorMethod<[string, string, string], undefined>,
  'applyForLoan' : ActorMethod<[string, string, string, number], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'creditMonthlyInterest' : ActorMethod<[string], number>,
  'deposit' : ActorMethod<[number, string, string], undefined>,
  'depositToSavings' : ActorMethod<[number, string], undefined>,
  'getAccountApplications' : ActorMethod<[], Array<AccountApplication>>,
  'getBalance' : ActorMethod<[], number>,
  'getBusinessAccount' : ActorMethod<[], BusinessAccount>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactForms' : ActorMethod<[], Array<ContactFormSubmission>>,
  'getLoanApplications' : ActorMethod<[], Array<LoanApplication>>,
  'getMyBusinessLoanApplications' : ActorMethod<
    [],
    Array<BusinessLoanApplication>
  >,
  'getPayrollHistory' : ActorMethod<[], Array<PayrollRecord>>,
  'getSavingsAccount' : ActorMethod<[], [] | [SavingsAccountInfo]>,
  'getSavingsTransactions' : ActorMethod<[], Array<Transaction>>,
  'getTransactions' : ActorMethod<[], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'openSavingsAccount' : ActorMethod<[string], SavingsAccountInfo>,
  'processPayroll' : ActorMethod<[string, number, string], undefined>,
  'recordIncomingBusinessPayment' : ActorMethod<
    [number, string, string, string],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'scheduleAdvisoryMeeting' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'sendBusinessPayment' : ActorMethod<
    [number, string, string, string],
    undefined
  >,
  'submitBusinessLoanApplication' : ActorMethod<
    [string, string, number, number, string, string],
    undefined
  >,
  'submitContactForm' : ActorMethod<[string, string, string], undefined>,
  'transferFromSavings' : ActorMethod<[number, string, string], undefined>,
  'withdraw' : ActorMethod<[number, string, string], undefined>,
  'withdrawFromSavings' : ActorMethod<[number, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];