/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ContactFormSubmission {
    name: string;
    email: string;
    message: string;
}
export interface SavingsAccountInfo {
    lastInterestCredited: string;
    balance: number;
    accountId: string;
    totalInterestEarned: number;
    createdAt: string;
    updatedAt: string;
    interestRate: number;
}
export interface BusinessPayment {
    date: string;
    recipient: string;
    description: string;
    amount: number;
}
export interface AdvisoryBooking {
    consultationTopic: string;
    name: string;
    businessType: string;
    preferredDate: string;
}
export interface BusinessAccount {
    incomingPayments: Array<BusinessPayment>;
    outgoingPayments: Array<BusinessPayment>;
    businessBalance: number;
}
export interface AccountApplication {
    fullName: string;
    email: string;
    accountType: string;
}
export interface LoanApplication {
    fullName: string;
    email: string;
    loanType: string;
    amount: number;
}
export interface BusinessLoanApplication {
    status: LoanStatus;
    businessName: string;
    businessType: string;
    submittedAt: string;
    loanAmountRequested: number;
    annualRevenue: number;
    loanPurpose: string;
}
export interface PayrollRecord {
    employeeName: string;
    salaryAmount: number;
    paymentDate: string;
}
export interface UserProfile {
    contactInfo: {
        email: string;
        countryCode: string;
        phone: string;
    };
    emailVerified: boolean;
    username: string;
    totpSecret: string;
    preferences: {
        notifPromo: boolean;
        notifTransactions: boolean;
        language: string;
        notifSecurity: boolean;
    };
    emailTwoFAEnabled: boolean;
    twoFAEnabled: boolean;
    twoFAMethod: string;
    personalInfo: {
        dob: string;
        country: string;
        city: string;
        postalCode: string;
        fullName: string;
        address: string;
        gender: string;
        lastName: string;
        firstName: string;
    };
    kycData: {
        dob: string;
        country: string;
        kycStatus: string;
        idNumber: string;
        idType: string;
    };
}
export interface Transaction {
    date: string;
    description: string;
    isDeposit: boolean;
    amount: number;
}
export enum LoanStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    adminGetAdvisoryBookings(): Promise<Array<AdvisoryBooking>>;
    adminGetAllBusinessLoanApplications(): Promise<Array<[Principal, Array<BusinessLoanApplication>]>>;
    adminUpdateBusinessLoanStatus(appIndex: bigint, newStatus: LoanStatus, user: Principal): Promise<void>;
    applyForAccount(fullName: string, email: string, accountType: string): Promise<void>;
    applyForLoan(fullName: string, email: string, loanType: string, amount: number): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    creditMonthlyInterest(currentDate: string): Promise<number>;
    deposit(amount: number, description: string, date: string): Promise<void>;
    depositToSavings(amount: number, date: string): Promise<void>;
    getAccountApplications(): Promise<Array<AccountApplication>>;
    getBalance(): Promise<number>;
    getBusinessAccount(): Promise<BusinessAccount>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getContactForms(): Promise<Array<ContactFormSubmission>>;
    getLoanApplications(): Promise<Array<LoanApplication>>;
    getMyBusinessLoanApplications(): Promise<Array<BusinessLoanApplication>>;
    getPayrollHistory(): Promise<Array<PayrollRecord>>;
    getSavingsAccount(): Promise<SavingsAccountInfo | null>;
    getSavingsTransactions(): Promise<Array<Transaction>>;
    getTransactions(): Promise<Array<Transaction>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    openSavingsAccount(currentDate: string): Promise<SavingsAccountInfo>;
    processPayroll(employeeName: string, salaryAmount: number, paymentDate: string): Promise<void>;
    recordIncomingBusinessPayment(amount: number, from: string, date: string, description: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    scheduleAdvisoryMeeting(name: string, businessType: string, consultationTopic: string, preferredDate: string): Promise<void>;
    sendBusinessPayment(amount: number, recipient: string, date: string, description: string): Promise<void>;
    submitBusinessLoanApplication(businessName: string, businessType: string, annualRevenue: number, loanAmountRequested: number, loanPurpose: string, submittedAt: string): Promise<void>;
    submitContactForm(name: string, email: string, message: string): Promise<void>;
    transferFromSavings(amount: number, toAccountId: string, date: string): Promise<void>;
    withdraw(amount: number, description: string, date: string): Promise<void>;
    withdrawFromSavings(amount: number, date: string): Promise<void>;
}
import type { BusinessLoanApplication as _BusinessLoanApplication, LoanStatus as _LoanStatus, SavingsAccountInfo as _SavingsAccountInfo, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async adminGetAdvisoryBookings(): Promise<Array<AdvisoryBooking>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAdvisoryBookings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAdvisoryBookings();
            return result;
        }
    }
    async adminGetAllBusinessLoanApplications(): Promise<Array<[Principal, Array<BusinessLoanApplication>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllBusinessLoanApplications();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllBusinessLoanApplications();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUpdateBusinessLoanStatus(arg0: bigint, arg1: LoanStatus, arg2: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateBusinessLoanStatus(arg0, to_candid_LoanStatus_n8(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateBusinessLoanStatus(arg0, to_candid_LoanStatus_n8(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async applyForAccount(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.applyForAccount(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyForAccount(arg0, arg1, arg2);
            return result;
        }
    }
    async applyForLoan(arg0: string, arg1: string, arg2: string, arg3: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.applyForLoan(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyForLoan(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async creditMonthlyInterest(arg0: string): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.creditMonthlyInterest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.creditMonthlyInterest(arg0);
            return result;
        }
    }
    async deposit(arg0: number, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deposit(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deposit(arg0, arg1, arg2);
            return result;
        }
    }
    async depositToSavings(arg0: number, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.depositToSavings(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.depositToSavings(arg0, arg1);
            return result;
        }
    }
    async getAccountApplications(): Promise<Array<AccountApplication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAccountApplications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAccountApplications();
            return result;
        }
    }
    async getBalance(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBalance();
            return result;
        }
    }
    async getBusinessAccount(): Promise<BusinessAccount> {
        if (this.processError) {
            try {
                const result = await this.actor.getBusinessAccount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBusinessAccount();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContactForms(): Promise<Array<ContactFormSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactForms();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactForms();
            return result;
        }
    }
    async getLoanApplications(): Promise<Array<LoanApplication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLoanApplications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLoanApplications();
            return result;
        }
    }
    async getMyBusinessLoanApplications(): Promise<Array<BusinessLoanApplication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBusinessLoanApplications();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBusinessLoanApplications();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPayrollHistory(): Promise<Array<PayrollRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayrollHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayrollHistory();
            return result;
        }
    }
    async getSavingsAccount(): Promise<SavingsAccountInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSavingsAccount();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSavingsAccount();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSavingsTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSavingsTransactions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSavingsTransactions();
            return result;
        }
    }
    async getTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactions();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async openSavingsAccount(arg0: string): Promise<SavingsAccountInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.openSavingsAccount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.openSavingsAccount(arg0);
            return result;
        }
    }
    async processPayroll(arg0: string, arg1: number, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.processPayroll(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processPayroll(arg0, arg1, arg2);
            return result;
        }
    }
    async recordIncomingBusinessPayment(arg0: number, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordIncomingBusinessPayment(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordIncomingBusinessPayment(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async scheduleAdvisoryMeeting(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.scheduleAdvisoryMeeting(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.scheduleAdvisoryMeeting(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async sendBusinessPayment(arg0: number, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendBusinessPayment(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendBusinessPayment(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async submitBusinessLoanApplication(arg0: string, arg1: string, arg2: number, arg3: number, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitBusinessLoanApplication(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitBusinessLoanApplication(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async submitContactForm(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactForm(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactForm(arg0, arg1, arg2);
            return result;
        }
    }
    async transferFromSavings(arg0: number, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.transferFromSavings(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transferFromSavings(arg0, arg1, arg2);
            return result;
        }
    }
    async withdraw(arg0: number, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.withdraw(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.withdraw(arg0, arg1, arg2);
            return result;
        }
    }
    async withdrawFromSavings(arg0: number, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.withdrawFromSavings(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.withdrawFromSavings(arg0, arg1);
            return result;
        }
    }
}
function from_candid_BusinessLoanApplication_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BusinessLoanApplication): BusinessLoanApplication {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_LoanStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoanStatus): LoanStatus {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SavingsAccountInfo]): SavingsAccountInfo | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _LoanStatus;
    businessName: string;
    businessType: string;
    submittedAt: string;
    loanAmountRequested: number;
    annualRevenue: number;
    loanPurpose: string;
}): {
    status: LoanStatus;
    businessName: string;
    businessType: string;
    submittedAt: string;
    loanAmountRequested: number;
    annualRevenue: number;
    loanPurpose: string;
} {
    return {
        status: from_candid_LoanStatus_n6(_uploadFile, _downloadFile, value.status),
        businessName: value.businessName,
        businessType: value.businessType,
        submittedAt: value.submittedAt,
        loanAmountRequested: value.loanAmountRequested,
        annualRevenue: value.annualRevenue,
        loanPurpose: value.loanPurpose
    };
}
function from_candid_tuple_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, Array<_BusinessLoanApplication>]): [Principal, Array<BusinessLoanApplication>] {
    return [
        value[0],
        from_candid_vec_n3(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): LoanStatus {
    return "pending" in value ? LoanStatus.pending : "approved" in value ? LoanStatus.approved : "rejected" in value ? LoanStatus.rejected : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, Array<_BusinessLoanApplication>]>): Array<[Principal, Array<BusinessLoanApplication>]> {
    return value.map((x)=>from_candid_tuple_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BusinessLoanApplication>): Array<BusinessLoanApplication> {
    return value.map((x)=>from_candid_BusinessLoanApplication_n4(_uploadFile, _downloadFile, x));
}
function to_candid_LoanStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LoanStatus): _LoanStatus {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LoanStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == LoanStatus.pending ? {
        pending: null
    } : value == LoanStatus.approved ? {
        approved: null
    } : value == LoanStatus.rejected ? {
        rejected: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
